### ISSUE TITLE
Modify position layout? tabbar hidden

### ISSUE THREAD

**Issue by eiosca** [octopitus/rn-sliding-up-panel#1]
Hi, Nice job.

I'm trying to use with react-native-router-flux but my tabbar disappear under this panel.

Do you have a solution?

Thk's

**Comment by octopitus** [comment]
You need to set `zIndex` of your tabbar to a number greater than 0.

**Comment by octopitus** [comment]
Btw, you should update to version 1.1.0. Then you can change the draggable area of the panel by using `draggableRange` property. Ex:
```js
<SlidingUpPanel
    draggableRange={{
        // I'm assuming 49 is the height of your tabbar
        top: Dimensions.get('window').height - 49
        bottom: 0
    }}
    visible>
    // ...
</SlidingUpPanel>
```
