### ISSUE TITLE
[Question][Possible improvement] Add callback to show method

### ISSUE THREAD

**Issue by filipef101** [octopitus/rn-sliding-up-panel#100]
Hello, great project.
I was wondering is it possible to have a callback on the show method?
Maybe also on close(I use the show method to close actualy btw)

**Comment by octopitus** [comment]
Can you [InteractionManager](https://facebook.github.io/react-native/docs/interactionmanager#docsNav) to schedule a task after the animation/interaction. Ex:

```js
// This method is called when you click a button to hide the panel
hidePanel() {
  this.panel.hide()

  InteractionManager.runAfterInteractions(() => {
    // ...a long-running synchronous task...
  });
}

```

**Comment by zapcriativo** [comment]
Hi!

How to show another panel after panel.hide event finish?

I try to hide panel, change component inside of current panel e show panel again with another height state but dont work :(
