### ISSUE TITLE
[Error] module:metro-react-native-babel-preset with Expo

### ISSUE THREAD

**Issue by cchini** [octopitus/rn-sliding-up-panel#101]
###  React-Native with Expo

I tried to install rn-sliding-up-panel but I have this problem to use it on my project.

Couldn't find preset "module:metro-react-native-babel-preset"

Version
"react": "^16.6.3",
"expo": "^30.0.1"
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"

**Comment by octopitus** [comment]
```bash
npm install metro-react-native-babel-preset
```

**Comment by thinhbui** [comment]
hi @octopitus, i installed metro-react-native-babel-preset but it's still error

**Comment by octopitus** [comment]
@thinhbui Hmmm, which version of `expo`? You may need to update to the latest version.

[Here](https://expo.io/@octopitus/SlidingUpPanel) is an example I built with Expo v32. Don't even need to install `metro-react-native-babel-preset` tho.

**Comment by octopitus** [comment]
Maybe something related to this? https://github.com/facebook/react-native/issues/21241
