### ISSUE TITLE
_this.panel.transitionTo is not a function

### ISSUE THREAD

**Issue by dotballV** [octopitus/rn-sliding-up-panel#111]
### Issue Description

_this.panel.transitionTo is not a function

![Simulator Screen Shot - iPhone 6 - 2019-04-12 at 10 16 27](https://user-images.githubusercontent.com/39124122/56012913-1849ef00-5d0c-11e9-9d3b-82407f00859e.png)

**Comment by herarya** [comment]
@dotballV hi how to you fix this

**Comment by zapcriativo** [comment]
@dotballV 

Hi, 

How to you fix this ?

**Comment by bashirpour** [comment]
@dotballV

Hi,
How to you fix this ?

**Comment by miguelsm** [comment]
It looks like `.transitionTo()` was renamed to `.show()` at some point, or at least it seems to behave in a similar way: https://octopitus.github.io/rn-sliding-up-panel/#showvalue-number-object
