### ISSUE TITLE
Initial value not respected

### ISSUE THREAD

**Issue by samiede** [octopitus/rn-sliding-up-panel#113]
### Issue Description

I'm setting the initial panel position the following way, it works when using it the first time. After I've changed screen with componentWillUnmount being called, the panel remains in the position I left it in when leaving the screen, even though the constructor is called again and _animatedValue has the correct value.

### Steps to Reproduce / Code Snippets / Screenshots

 ```js                                                         
  constructor (props) {
    super(props)
    this.draggableRange = {
      bottom: 100,
      top: height - StatusBar.currentHeight - 60
    }
    this._animatedValue = new Animated.Value(windowHeight / 2)
  }


  <SlidingUpPanel
          showBackdrop={false}
          onBackButtonPress={() => true}
          animatedValue={this._animatedValue}
          draggableRange={this.draggableRange}
          snappingPoints={[100, height / 2, height]}>
          {(dragHandlers) => ( .... )

/>
```                                                           

---
### Environment
* Version: latest
* React Native version: 0.57.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): OnePlus

**Comment by octopitus** [comment]
Investigating. For now a workaround is to [reset the animation](https://facebook.github.io/react-native/docs/animatedvalue#resetanimation) to default value when your component will unmount.

Put this to your component:

```js
componentWillUnmount() {
  this._animatedValue.resetAnimation()
}
```

**Comment by samiede** [comment]
I fear that this has something to do with my own implementation because your workaround works exactly once and then doesn’t when going to the screen again

**Comment by samiede** [comment]
Update from my side:

I had an @autobind decorator in that screen that apparently caused the behavior. Removing that and binding all functions manually resolved the issue! 
Thanks!

**Comment by faustoct** [comment]
animatedValue is not working for me.
`animatedValue={top}`but is render like bottom

**Comment by Whysp3r** [comment]
I'm currently experiencing the same issue. My component is correctly initialized the first time but after it will unmount and did mount again (life cycle is the same as the first time), the position isn't correctly initialized the second time even if the state is the same.
