### ISSUE TITLE
Detect touch on Backdrop

### ISSUE THREAD

**Issue by zamhaq** [octopitus/rn-sliding-up-panel#115]
### Issue Description

How to detect a touch a on `backdrop` and close panel based on `backdrop` touch?

### Steps to Reproduce / Code Snippets / Screenshots
 Touch on the backdrop when panel is open

There was already a resolved issue here: https://github.com/octopitus/rn-sliding-up-panel/issues/15

But it would be great to have it in the docs since I could not find out the prop `onRequestClose` in the docs.

Edit:- `onRequestClose` does not fire in this version? It is not called when I touch on the backdrop.

---
### Environment
* Version: 1.2.1
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XR

**Comment by octopitus** [comment]
Have you try upgrading to v2?

**Comment by zamhaq** [comment]
@octopitus from your changelog https://github.com/octopitus/rn-sliding-up-panel/blob/master/CHANGELOG.md#breaking-changes, it says `Remove the visible and onRequestClose props. The component now will always be rendered, below the screen. Use show() & hide() to control panel position.`. So if I upgrade to v2 will I be getting access to this props?

**Comment by octopitus** [comment]
Yes ;). Via the `ref`. Usage & examples are in README.

**Comment by zamhaq** [comment]
@octopitus but in that case, how do I detect the touch on the backdrop? Your answer in the other issue was to use `onRequestClose`.

Thanks.

**Comment by octopitus** [comment]
You want to detect the touch on backdrop to close the panel, right? Or want to do something else?

**Comment by zamhaq** [comment]
> You want to detect the touch on backdrop to close the panel, right? Or something else?

yes

**Comment by octopitus** [comment]
Then just upgrade to v2. The panel should close automatically when touching on the backdrop.

**Comment by zamhaq** [comment]
oh. Sorry I noticed this yesterday but It was crashing for me. Anyways thank you so much @octopitus
