### ISSUE TITLE
Touchable inside dragHandler

### ISSUE THREAD

**Issue by quantosapplications** [octopitus/rn-sliding-up-panel#120]
Hello, I have some touchable inside the dragHandler and then a scrollview.
The situation is similar to your Scrollview example except that in the dragHandler area there is a TouchableOpacity at the center.
The panel is sliding between the middle of the screen and the top.

When I try to slide up panel pressing in the touchable area and then slide up an error occur.

![Simulator Screen Shot - iPhone 8 - 2019-05-16 at 18 07 53](https://user-images.githubusercontent.com/47910896/57869541-8a2ec000-7805-11e9-88f4-82633b840a09.png)

Nothing happen instead if I first drag the panel using an area not covered by any touchable. After doing that I can also drag the panel around pressing on a touchable.

**Comment by quantosapplications** [comment]
SOLVED this adding 
`    this._initialDragPosition = animatedValue`
in the constructor.

**Comment by JohnKim7** [comment]
Check out my PR #122
