### ISSUE TITLE
Using with react-native-swiper

### ISSUE THREAD

**Issue by lkoehl** [octopitus/rn-sliding-up-panel#123]
### Issue Description

I am desperately trying to use the rn-sliding-up-panel with the react-native-swiper but both combined doesn't seem to work. It seems like only the rn-sliding-up-panel works while the swiper stopped working. The Touch Events doesn't reach the swiper.  Your fix in #47 doesn't work because every time the state changes my View gets rerendered which is too resource intensive.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
<SlidingUpPanel
    draggableRange={{ top: 266, bottom: 0 }}
    snappingPoints={[0, 266]}
>
    <MyCustomFooter/>
    <Settings />
</SlidingUpPanel>
```

Where the Footer contains a horizontal swiper and the Settings should come up on vertical touch input.

**Comment by octopitus** [comment]
Thanks for reporting this @lkoehl. Can you help to test on `v2.2.2-rc1`?

**Comment by lkoehl** [comment]
Works on `v2.2.2-rc1` Thank you
