### ISSUE TITLE
Very slow animation

### ISSUE THREAD

**Issue by pkt-dev** [octopitus/rn-sliding-up-panel#125]
### Issue Description
When calling show or close some times the animation is extremely slow.

### Steps to Reproduce / Code Snippets / Screenshots

```js
<SlidingUpPanel
  showBackdrop={false}
  draggableRange={this.slideUpRange}
  animatedValue={this.draggedValue}
  allowDragging={false}
  ref={c => this.slideUpPanel = c}>

    {dragHandler => (
      <View style={[styles.slidingPanelContainer]}>
        <View style={styles.dragHandler} {...dragHandler}>
          {this.renderPanelPositionIcon()}
        </View>

         {this.renderPanelData()}
      </View>
  )}

</SlidingUpPanel>
```

---
### Environment
* Version: 2.2.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 8 Debug

**Comment by yanuwar** [comment]
+1

**Comment by yemi** [comment]
+1

**Comment by pkt-dev** [comment]
Any help on this would be greatly appreciated. It doesn't matter the content. Android is pretty consistently extremely slow. I animate to 150 when I click on a map marker, and then have another button to make it animate to the top of the screen to show more details. Even without all of the data its still very slow.

**Comment by vgb0332** [comment]
Have you been testing with the debugger on? RN with js-debugger on will generally slow down any type of animation from my experience.

**Comment by pkt-dev** [comment]
Yes, I have debugging on. I turned it off, and the animation is much smoother. However, it doesn't really help when we are developing to have an animation going unbearably slow.

**Comment by vgb0332** [comment]
That is true, but i haven't find a way to have smooth animation while debugger on since RN came out.
What I usually do is test for all the data process before applying any animation to the component or using Alert to display certain data if needed with debugger off(ex, Alert.alert(some data to display))

**Comment by pkt-dev** [comment]
Thanks @vgb0332. I will attempt to do that.

**Comment by saiyam-sage** [comment]
I am also facing this issue, When calling the show or close the animation is extremely slow.

**Comment by saiyam-sage** [comment]
@pkt-dev  have you any idea about this problem ?

**Comment by moxorama** [comment]
I think the one solution is rewrite animation with react-native-reanimated ;(

**Comment by saiyam-sage** [comment]
the problem is with when we use setstate or redux dispatch before show or close

**Comment by cihanbas** [comment]
@saiyam-sage Thank you for your help, when I use panel.show() after setState it is too slow, but
 ı use before setState it is good working

**Comment by saiyam-sage** [comment]
yes need to use react-native-reanimated

**Comment by davidsmall89** [comment]
I resolved this by making hide a callback in setState:
`this.setState(
      { sortsMenu: newSort },
      this.slideUpPanel.hide
    )`

**Comment by octopitus** [comment]
I would recommend you schedule your works to run after the animation has finished using (InteractionManager)[https://facebook.github.io/react-native/docs/interactionmanager].

```js
InteractionManager.runAfterInteractions(() => {
  // ...long-running synchronous task...
});

this.panelRef.show() // Or hide(). panelRef holding the reference the SlidingUpPanel component.
```

Since the entire animation is running in Javascript thread. Other scripts might occupy the thread and make the animation doesn't look smooth.

**Comment by saiyam-sage** [comment]
@octopitus yes its works Thanks :)

**Comment by saiyam-sage** [comment]
@octopitus but runAfterInteractions() is not fired sometime

**Comment by saiyam-sage** [comment]
@octopitus `runAfterInteractions()` is not always calling.

**Comment by octopitus** [comment]
@saiyam-sage this might be related https://github.com/facebook/react-native/issues/8624

**Comment by jordangrant** [comment]
Was extremely slow for me on Android.
I had 
`const animatedValue = new Animated.Value(1);`
and 
`animatedValue={animatedValue}` as a prop and it **murdered** performance
don't do that.

**Comment by teo029** [comment]
Couldn't solve it in any way. Seems like something in the background (requests, maybe) block the main thread and slows this animation. Other SlidingMenu packages worked well, seems related to how the animations are initialized.

**Comment by p-mob2015** [comment]
Try wrapping the show/hide call in a setTimeout. It works much better and consistent.
Reason? Maybe the animation getting off from the normal execution queue and makes sure the all the current synchronous calls are finished. No lock.

**Comment by nicost71** [comment]
I managed to get it working by running the show/hide in a javaScript setTimeout like this:

      setTimeout(() => {
        panelRef?.hide();
      });

**Comment by gilsonviana** [comment]
I was having the same issue while running on *Expo Client* while *remote debugging*. Disabling it solved the problem for me.

**Comment by 29er** [comment]
i ended up using 'reanimated-bottom-sheet' as none of these attempts fixed preformance issues on Androi.

**Comment by iway1** [comment]
@29er Thanks so much for pointing me towards this library. I've spent more time than I care to admit trying to get `rn-sliding-up-panel` to work properly and it just consistently causes so many issues. For instance if you have multiple panels, calling `.show()` on one of them will show every panel. Like, why? `reanimated-bottom-sheet` works much better.

**Comment by kimkong88** [comment]
@29er Thanks, I guess I have to migrate to reanimated-bottom-sheet as well.. pretty painful since my entire app is relying on this library :(
