### ISSUE TITLE
SlideUpPanel loads before .show() & doesn't allow 2 panels

### ISSUE THREAD

**Issue by Zontex** [octopitus/rn-sliding-up-panel#137]
### Issue Description

The rn-sliding-up-panel library is super important component in my app so first of all I would like to thank the developer for keep maintaining this and bringing this solution to the community.

while working with the component I found out 2 issues when I would like to bind 2 different slide-up-panels at the same page, each slide-up panel will show up by calling separate function.

1. The entire slideup component loads when the screen loads, even those this._panel.show() wasn't executed. this makes the app slower and produce more views even when unnecessary. it will not show the panel but it will render it inside the screen. (checked by running alert() inside the slide-up component)

2. when using 2 slide-up components with different ref function, by calling one of them it will automatically render the second one on top of the first one, even tho their ref is completely different.

### Steps to Reproduce / Code Snippets / Screenshots
First slide-up panel
```js
<SlidingUpPanel
        style={{backgroundColor: 'rgb(255,255,255)'}}
        allowDragging={false}
        showBackdrop={true}
        ref={(c) => {
          this._firstPanel = c
        }}>
```
Second slide-up panel
```js
<SlidingUpPanel
        style={{backgroundColor: 'rgb(255,255,255)'}}
        allowDragging={false}
        showBackdrop={true}
        ref={(b) => {
          this._secondPanel = b
        }}>
```

By executing this._firstPanel.show() it will show the second panel on top of the first panel.

---
### Environment
* Version: Latest
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device (both android and iOS) on debug version.

**Comment by octopitus** [comment]
Duplicated #132

**Comment by Zontex** [comment]
> Duplicated #132

Working perfectly. I suggest you could add this information to the description in the README file :) would help a lot and save time searching and trying ...
