### ISSUE TITLE
not showing at all with bottom tab in Android

### ISSUE THREAD

**Issue by thegreatLSJ** [octopitus/rn-sliding-up-panel#139]
### Issue Description

react-native: 0.60.3
rn-sliding-up-panel: ^2.3.1

test device & emulator :  both Galaxy S7 Android API 26

literally the SlidingUpPanel component isn't showing at all in react-navigation's bottomTabNavigation's screen in Android while working perfect in iOS. 

was testing on iOS firstly and made it work perfect already, and tried almost everything(read all opened and closed issues related Android in Issues) to try to solve this problem, but nothing worked :(

by the way, it was strange that *scrollIntoView* method made app crash sometimes.
(it didn't fix the problem when it worked tho.)

any help or fix would be so much appreciated and thank you for this great library !

### Steps to Reproduce / Code Snippets / Screenshots

```js                                 
<View style={{ flex: 1 }}>
      <SafeAreaView style={{ paddingTop: Header.HEIGHT }}>
      </SafeAreaView>

      <SlidingUpPanel
        containerStyle={{ flex: 1 }}
        ref={slidingPanelElement}
        animatedValue={draggedAnimatedValue}
        draggableRange={draggableRange}
        snappingPoints={
          Platform.select({
            ios: [
              (Dimensions.get('window').height - getStatusBarHeight() - Header.HEIGHT) / 3 + getBottomSpace(),
              Dimensions.get('window').height - getStatusBarHeight() - Header.HEIGHT
            ],
            android: [
              (Dimensions.get('screen').height - Header.HEIGHT) / 3,
              Dimensions.get('screen').height - Header.HEIGHT,
            ],
          })
        }
        friction={0.6}
        showBackdrop={true}
      >
        <View style={{ flex: 1, backgroundColor: '$white', }} />
      </SlidingUpPanel>

    </View>
```                                                           

---
### Environment
* Version: ^2.3.1
* React Native version: 0.60.3
* Platform(s) (iOS, Android, or both?): Android API 26, Galaxy S7
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Emulator both / Debug

**Comment by thegreatLSJ** [comment]
self found solution:

SlidingUpPanel doesn't show in TabNavigator made by react-navigation's *createBottomTabNavigator* .

so I tried to change the TabNavigator to make with createMaterialTopTabNavigator and add navigator config
```js
  tabBarPosition: 'bottom' 
```
, then it worked :)

**Comment by octopitus** [comment]
@thegreatLSJ Have you tried to move the panel to the bottom most of components hierarchy, bellow the navigation stack?

```jsx
render() {
  return (
    <>
      <NavigationStack />
      <SlidingUpPanel />
    </>
  )
}

**Comment by thegreatLSJ** [comment]
> @thegreatLSJ Have you tried to move the panel to the bottom most of components hierarchy, bellow the navigation stack?
> 
> ```js-jsx
> render() {
>   return (
>     <>
>       <NavigationStack />
>       <SlidingUpPanel />
>     </>
>   )
> }
> ```

nah in my case the SlidingUpPanel should be inside a screen in bottom tab navigator.
but it works inside a screen in material top tab navigator.

**SUMMARY** :
SlidingUpPanel inside a  react-navigation BottomTabNavigator - works only in iOS.
SlidingUpPanel inside a  react-navigation MaterialTopTabNavigator - works in Android (didn't test in iOS yet).

for all who wanna see how I'm personally dealing with it, here's my code.
any idea for better one is welcome ;)

```js
import { createBottomTabNavigator, createMaterialTopTabNavigator, } from 'react-navigation';

const RouteConfigs = { ... };
const TabNavigatorConfigIOS = { ... };
const TabNavigatorConfigAndroid = {
  tabBarPosition: 'bottom',
  ...
};

const MainTabNavigatorIOS = createBottomTabNavigator(RouteConfigs, TabNavigatorConfigIOS);
const MainTabNavigatorAndroid = createMaterialTopTabNavigator(RouteConfigs, TabNavigatorConfigAndroid);

const MainTabNavigator = Platform.select({
  ios: MainTabNavigatorIOS,
  android: MainTabNavigatorAndroid,
});

export default MainTabNavigator;
```

**Comment by octopitus** [comment]
Thanks. Let me add this to the document.

**Comment by thegreatLSJ** [comment]
> Thanks. Let me add this to the document.

you're welcome. of course!
