### ISSUE TITLE
If sliding for ScroolView, scrollView swipes up how to slide itself.

### ISSUE THREAD

**Issue by liliangzdh** [octopitus/rn-sliding-up-panel#14]

**Comment by wmt-iOS-Harpal** [comment]
I Want to put scrollview in sode slider but it not scroll.
how to put scrollview in silde scrollView ??!!

**Comment by octopitus** [comment]
You must enable/disable `allowDragging` manually like so:
```jsx

_onScroll({ nativeEvent }) {
  if (nativeEvent.contentOffset.y <= 0 || !this.state.allowDragging) {
    this.setState({ allowDragging: true });
  }
}

_ignoreScrollBehavior() {
  if (this.state.allowDragging) {
    this.setState({ allowDragging: false });
  }
}


<SlidingUpPanel allowDragging={this.state.allowDragging}>
  <ScrollView
    scrollEventThrottle={16}
    onScroll={this._onScroll}
    onTouchMove={this._ignoreScrollBehavior}>
    // ...
  </ScrollView>
</SlidingUpPanel>
```

**Comment by octopitus** [comment]
Basic idea is, when ScrollView reaches the top, enable dragging, otherwise, disable it. 

But I guess things will get more complicated. When the panel is on the middle of animation, you shouldn't disable it. When scrollview at the bottom, scroll up will cause panel to move, not ScrollView. etc...

**Comment by ravernkoh** [comment]
Is there a way to only enable dragging the panel in the top bar?

**Comment by ravernkoh** [comment]
Is there a way to limit the size of the draggable area? For example, if the entire panel is 300*500, is there a way to limit the gesture recogniser size to (0, 0, 300, 200)?
