### ISSUE TITLE
Detect when reach top/bottom sliding up and down

### ISSUE THREAD

**Issue by faustoct** [octopitus/rn-sliding-up-panel#140]
I didn't find the correct way to add listener to get notified when slide panel reach the bottom and top . Is there any doc of it?

**Comment by faustoct** [comment]
Closing it, found it here! tkx
https://github.com/octopitus/rn-sliding-up-panel/pull/110

**Comment by Drzaln** [comment]
Hi, can you explain me ho to solve it?

**Comment by Orawko** [comment]
dariothornhill PR helped me achieve that behaviour https://github.com/octopitus/rn-sliding-up-panel/pull/186/commits/a5e0b31f0212aeb98db86fd91b2faa5b27c108f8
