### ISSUE TITLE
Module loading error with Expo Web / react-native-web

### ISSUE THREAD

**Issue by vjsingh** [octopitus/rn-sliding-up-panel#143]
### Issue Description

When importing this library in Expo Web I get the below error:

```
Failed to compile
.../node_modules/rn-sliding-up-panel/SlidingUpPanel.js 35:19
Module parse failed: Unexpected token (35:19)
You may need an appropriate loader to handle this file type.
| 
| class SlidingUpPanel extends React.PureComponent {
>   static propTypes = {
|     height: PropTypes.number,
|     animatedValue: PropTypes.instanceOf(Animated.Value),
This error occurred during the build time and cannot be dismissed.
```

---
### Environment
Expo SDK 33 on web

### Solution?
Per this issue: https://github.com/react-native-web-community/react-native-web-linear-gradient/issues/1

This may be the fix needed:

> This package needs to compile its modules to ES5 and point the package.json entry file to a commonjs module.

**Comment by arch10** [comment]
@octopitus Any update on this? Getting the same error with expo SDK 36.

**Comment by octopitus** [comment]
@arch10 Try adding this to your app.json

```json
{
  "expo": {
    "web": {
      "build": {
        "babel": {
          "include": ["rn-sliding-up-panel", "static-container"]
        }
      }
    }
  }
}
```

**Comment by arch10** [comment]
Thanks @octopitus !! It worked !!
