### ISSUE TITLE
Close panel when tap on backdrop

### ISSUE THREAD

**Issue by MyTotoro** [octopitus/rn-sliding-up-panel#15]
Any way to close panel with tapping on the backdrop - either as a prop or catching event programatically

The biggest issue here is that the user can swipe the panel down (but not completely closed) they might not realize it's there. Their first gesture afterwards is to tap on the screen like normal (the backdrop) and expect it to respond

**Comment by octopitus** [comment]
When you swipe down or tap on the backdrop `onRequestClose` event will fire. You should remember to update `visible` prop to false. Like this:

```jsx
<SlidingUpPanel
  visible={this.state.visible}
  onRequestClose={() => this.setState({visible: false})}
/>
```
