### ISSUE TITLE
Backdrop not full if another component using elevation

### ISSUE THREAD

**Issue by Drzaln** [octopitus/rn-sliding-up-panel#159]
### Issue Description

Hi, i'm facing some issue if using elevation on certain component, the backdrop hiding in that component.

This is some screenshot from Iphone X emulator

![Simulator Screen Shot - iPhone X - 2020-01-14 at 14 46 12](https://user-images.githubusercontent.com/33492469/72324682-0f90aa00-36de-11ea-9d20-a0c7c9f22209.png)

the backdrop hiding below the appbar. I have tried to use zIndex inside backdropStyle, but that doesn't affect anything.

**Comment by octopitus** [comment]
In case you are using react-navigation, you should move the panel to bottom of the component hierarchy. Something like [this](https://github.com/octopitus/rn-sliding-up-panel/issues/42#issuecomment-375859133)

**Comment by Drzaln** [comment]
Wow, that's work. Thank you. I will close this issue
