### ISSUE TITLE
Need some help.. 

### ISSUE THREAD

**Issue by AnshuGoyal** [octopitus/rn-sliding-up-panel#16]
The way we can drag the panel to bottom after it appears on the screen......can we do the same dragging by pulling the panel from bottom instead on tapping on "Show Panel". I want to implement vertical swiping kind of thing on android. Any help ?

**Comment by Bobobrien92** [comment]
By your description I think this is related to https://github.com/octopitus/rn-sliding-up-panel/issues/48
