### ISSUE TITLE
Panel come up when very bottom text field get focused

### ISSUE THREAD

**Issue by Drzaln** [octopitus/rn-sliding-up-panel#168]
### Issue Description
<img src="https://user-images.githubusercontent.com/33492469/78661154-7944dc80-78f8-11ea-8e11-7ac74bcc0fff.png" height="300" />

when focused to Fullname text field or text field near bottom screen, panel always come up like this

<img src="https://user-images.githubusercontent.com/33492469/78661805-9928d000-78f9-11ea-81d7-febd90910958.png" height="300" />

i have placed the panel outside main View, but that's doesn't work at all.

### Environment
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): both

**Comment by octopitus** [comment]
Fixed in v2.4.2.
