### ISSUE TITLE
Can't see anything inside my views

### ISSUE THREAD

**Issue by GokulRG** [octopitus/rn-sliding-up-panel#18]
Following the exact code snippet from the example, Cannot see anything inside my views

**Comment by octopitus** [comment]
Sorry for the long silence @GokulRG. Can I have your RN version, OS and device version?

**Comment by kaynz** [comment]
Same here. Latest RN Version, Linux, 7.1.1.

**Comment by kaynz** [comment]
@octopitus Does this look right? https://paste.xinu.at/g5AAFz/

**Comment by smith64fx** [comment]
Same problem here :/

**Comment by octopitus** [comment]
🤔 I've tested it on Nexus 5X & Lenovo K8 Note, Android 7.1, RN version 50.4, still works.
