### ISSUE TITLE
ViewPropTypes has been removed from React Native

### ISSUE THREAD

**Issue by Shrroy** [octopitus/rn-sliding-up-panel#215]
I just installed `rn-sliding-up-panel` on the lastest version of react-native but I'm getting the following error

>  ERROR  Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

```
    "rn-sliding-up-panel": "^2.4.5"
    "react": "18.0.0",
    "react-native": "0.69.1",
```

I tried to install the latest version of `rn-sliding-up-panel` and still getting same error

**Comment by octopitus** [comment]
@Shrroy Fixed in 2.4.6
