### ISSUE TITLE
Back button does not hide the sliding panel when allowDragging is false on Android

### ISSUE THREAD

**Issue by abiduzz420** [octopitus/rn-sliding-up-panel#23]
The application closes when I hit back button. I also defined the onRequestClose prop but the issue is still there.
`onRequestClose={() => this._panel.transitionTo(this.props.draggableProps.bottom)}`

**Comment by octopitus** [comment]
You can manually handle back button behavior. Something like this:
```js
BackHandler.addEventListener('hardwareBackPress', () => {
  // _panel holding ref to SlidingUpPanel
  if (this.state.visible) {
    this._panel.transitionTo(0);
    return true;
  }

  return false;
});
```

**Comment by AsadSaleh** [comment]
But right now, we don't have state anymore right? How can I return false when the panel is already invisible?

**Comment by octopitus** [comment]
@AsadSaleh You're right.

**Comment by octopitus** [comment]
@AsadSaleh Checkout version v2.1.
