### ISSUE TITLE
bottom sheet without covering content

### ISSUE THREAD

**Issue by juliangruber** [octopitus/rn-sliding-up-panel#25]
Currently as in the bottom sheet demo you can't interact with anything beside the bottom sheet, as the `styles.container` is covering the whole page.

Is there a way to be able to interact with components lying behind it?

**Comment by juliangruber** [comment]
I've tried multiple approaches, like dynamic z-index changes and dynamic `styles.container` dimensions, but none worked well.

**Comment by octopitus** [comment]
🤔 I will look into this.

**Comment by octopitus** [comment]
@juliangruber @amestsantim Did you guys disable backdrop (`showBackdrop={false}`)?

**Comment by juliangruber** [comment]
yes

**Comment by octopitus** [comment]
And remember to put the panel at the end of your components tree.
```jsx
<View style={styles.container}>
  // Your other components...
  <SlidingUpPanel>
    // Content
  </SlidingUpPanel>
</View>
```
It won't overlap the other elements.
