### ISSUE TITLE
isPanelClosed ???

### ISSUE THREAD

**Issue by EDUARDOVILLALPANDOMELLO** [octopitus/rn-sliding-up-panel#28]
Currently, when the prop `showBackdrop` is set to true, the panel can be _dismissed_ by tapping on the backdrop. However, is there any way to know _**when**_ that happens? 

I know it can be opened through `this._panelRef.transitionTo(n)`. where n is the position of the panel. Is there a way to do it the other way around so that it returns n at any given time? (And thus know if it is closed?)

Or maybe, is there a way to add an event listener (onPress) to the backdrop itself???

**Comment by EDUARDOVILLALPANDOMELLO** [comment]
After looking at the code, I find the solution. I post it here in case anyone may need it in the future. It is a property not listed in the docs, but present in the code; it is `onRequestClose`

**Comment by octopitus** [comment]
Opps, sorry, forgot to write document for it. Will add asap.
