### ISSUE TITLE
Issues with RN 0.51 version

### ISSUE THREAD

**Issue by simonedavico** [octopitus/rn-sliding-up-panel#29]
I am trying to implement the demo example on the latest version of React-Native, but it seems like the component has some issues, mostly with drag handlers not working properly. Perf monitor shows also a lot of dropped frames while interacting with the panel. I know RN 0.51 made some changes in regards to layout dimensions computations, so this may be related?

**Comment by octopitus** [comment]
Do you still have the problem, @simonedavico? I just tested on RN 0.54 (use the demo code) and it works fine.
