### ISSUE TITLE
TransitionTo might not work when AllowMomentum is true

### ISSUE THREAD

**Issue by jaycee425** [octopitus/rn-sliding-up-panel#3]
Having a transitionTo(0) inside a onDragEnd function for example, if the allowMomentum is on true it will not  work. Is this expected behavior? Im actually busy with work but if I dont forget about it  I would like to take a look on it :D

**Comment by octopitus** [comment]
Yes, you're right. Let me have a look at it when I have time. For now a workaround solution is just disable momentum (`allowMomentum={false}`).

**Comment by samschooler** [comment]
Do we know what is causing this? I'd love to fix the issue. @octopitus have you looked into it yet?

**Comment by octopitus** [comment]
Fixed #12. Great thanks to @samschooler.
