### ISSUE TITLE
SlidingUpPanel doesn't show if visible property is set to true initially

### ISSUE THREAD

**Issue by dchhetri** [octopitus/rn-sliding-up-panel#30]
From testing, when setting visible to true on initial creation `<SlidingUpPanel visible={true}> ... </SlidingUpPanel>` nothing gets rendered. Is this supported? Or does it always have to start of with `visible={false}`

**Comment by EDUARDOVILLALPANDOMELLO** [comment]
Try setting draggableRange bottom to a value other than 0 (which is default)

**Comment by dchhetri** [comment]
That doesn't seem to work, although it does have effect if SlidingUpPanel visible is set to false then true, it doesn't have any effect if SlidingUpPanel is initialized with visible set to true.
