### ISSUE TITLE
How to create two or more "levels" for the panel to show 

### ISSUE THREAD

**Issue by cosio55** [octopitus/rn-sliding-up-panel#31]
Hello, I wanted to know if there's a way to show the panel first as a preview and then when the user clicks on a button or drags it upwards to show the rest of it, like in this examples:

![a9f3ae52-c766-11e6-9423-3c6d97b4843f](https://user-images.githubusercontent.com/933413/34587809-7e183f1c-f16f-11e7-9ef3-e54d4ffe40bc.gif)

Or this one from your inspiration:

![68747470733a2f2f7261772e6769746875622e636f6d2f756d616e6f2f416e64726f6964536c6964696e67557050616e656c44656d6f2f6d61737465722f736c6964696e67757070616e656c2e706e67](https://user-images.githubusercontent.com/933413/34587832-9196a3d0-f16f-11e7-8170-0a0130ab5225.png)

**Comment by yvasiuk-sphere** [comment]
If I understand you correctly, your answer somewhere in this closed issue: https://github.com/octopitus/rn-sliding-up-panel/issues/55

**Comment by octopitus** [comment]
Sorry for the long silence. If you are still interested, you can follow this example:

```jsx
const {height} = Dimensions.get('window')

<SlidingUpPanel
  ref={c => this._panel = c}
  draggableRange={{top: height, bottom: 120}}
  visible={hasDataForPokemon()}
  startCollapsed>
 <Button onPress={() => this._panel.transitionTo(height)} />
</SlidingUpPanel>
```

**Comment by zapcriativo** [comment]
@octopitus 

Hi, congrats for your work!

I try to use transitionTo, but return this error...

How to fix this?

<img width="363" alt="image" src="https://user-images.githubusercontent.com/7153803/68350380-df75cb00-00de-11ea-8c5b-a6a148350bc8.png">
