### ISSUE TITLE
Keyboard doesn't push slider

### ISSUE THREAD

**Issue by sofaws** [octopitus/rn-sliding-up-panel#32]
Hello,

I have inputs in my slider but when I press and the keyboard opens, the slider is not pushed up (So the field is hidden by the keyboard). Note that my menu and map of behind is well pushed.
How to change this behavior? thank you very much

![27604839_10213636425600161_1624458467_o](https://user-images.githubusercontent.com/14289013/35611714-3cfb7484-0666-11e8-8b0a-b4f7e18607b6.jpg)
![27537326_10213636425640162_542944887_o](https://user-images.githubusercontent.com/14289013/35611713-3bdaabce-0666-11e8-98f0-9d8b4254413c.jpg)

**Comment by renanboni** [comment]
Had you have figured out how to solve this problem? I got the same here.  @sofaws

**Comment by nasungtae** [comment]
<KeyboardAvoidingView style={styles.bottomView}
keyboardVerticalOffset={Platform.OS == 'ios'? 100 : 110 }
behavior="padding" enabled>
{contents...}
</KeyboardAvoidingView>

**Comment by octopitus** [comment]
Close as it's fixed in v2.
