### ISSUE TITLE
Error when run android

### ISSUE THREAD

**Issue by falbertp** [octopitus/rn-sliding-up-panel#33]
Hi got error when running yarn run:android, please help
 
ERROR  EPERM: operation not permitted, lstat 'D:\Frank\workspace\rnmap\example\
android\app\build\intermediates\res\merged\debug\anim'
npm ERR! code ELIFECYCLE
npm ERR! errno 11
npm ERR! react-native-maps@0.19.0 start: `node node_modules/react-native/local-c
li/cli.js start`
npm ERR! Exit status 11
npm ERR!
npm ERR! Failed at the react-native-maps@0.19.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-01-31T10_17_38_
735Z-debug.log

[2018-01-31T10_17_38_735Z-debug.log](https://github.com/octopitus/rn-sliding-up-panel/files/1681284/2018-01-31T10_17_38_735Z-debug.log)

react-native-cli: 2.0.1
react-native: 0.51.0
npm version
{ 'react-native-maps': '0.19.0',
  npm: '5.5.1',
  ares: '1.13.0',
  cldr: '32.0',
  http_parser: '2.7.0',
  icu: '60.1',
  modules: '59',
  nghttp2: '1.25.0',
  node: '9.2.0',
  openssl: '1.0.2m',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.16.1',
  v8: '6.2.414.44-node.11',
  zlib: '1.2.11' }

**Comment by octopitus** [comment]
It's not a problem with this library. Check your permission.
