### ISSUE TITLE
Limit size of the draggable area

### ISSUE THREAD

**Issue by nicomazz** [octopitus/rn-sliding-up-panel#34]
I have a map and a scrollview. If I make the sliding view draggable then I can not move the scrollview. It would be useful to make only a certain area draggable, in order not to prevent scrollview operation.

![simulator screen shot 21 feb 2018 01 48 08](https://user-images.githubusercontent.com/4215054/36457236-478085a4-16a9-11e8-9292-2647733074ef.png)

**Comment by Bobobrien92** [comment]
You can listen for onTouchStart/End/1 more triggers for a scrollview in the panel's component.  When those 3 triggers are changed make the state of the sliding-up-panel allowDrag true/false.

**Comment by octopitus** [comment]
Added a [demo](https://github.com/octopitus/rn-sliding-up-panel/blob/master/demo/ScrollViewInsidePanel.js) and to the doc :')
