### ISSUE TITLE
Ambiguous resolution: react-native module

### ISSUE THREAD

**Issue by huy-lv** [octopitus/rn-sliding-up-panel#38]
I got this problem after install this lib (v1.1.9) on android
`Ambiguous resolution: module '...\App.js' tries to require 'react-native', but there are several files providing this module. You can delete or fix them
`
I found a temp resolution, remove the react-native folder inside `/node_modules/rn-sliding-up-panel/node_modules/`
Please fix this problem
![29468162_226681067891451_5144797137531305984_o](https://user-images.githubusercontent.com/7688070/37642569-2956d6ac-2c50-11e8-847f-caec75106c57.png)

**Comment by octopitus** [comment]
Hey @huy-lv , thanks for reporting. Will fix this right now.

**Comment by dylancompanjen** [comment]
I'm getting this error as well.

**Comment by octopitus** [comment]
@dylancompanjen this is fixed in version 1.1.10
