### ISSUE TITLE
Allow swipe up and down

### ISSUE THREAD

**Issue by huy-lv** [octopitus/rn-sliding-up-panel#39]
Hey, please add a prop allowing user swipe up to expand and swipe down to close, i mean do not allow slide to a position between <height> and 0.

**Comment by dylancompanjen** [comment]
I would like this feature too, as seen in for e.g. the music player in Spotify & Apple Music.

**Comment by octopitus** [comment]
You can manually call to `transactionTo` inside `onDragEnd` event (It's invoked with the current position of the panel) with some conditions e.g. did user scroll over half of draggable range? If yes, then scroll to top, otherwise scroll back to bottom.

```jsx
_onDragEnd(position) {
  if (position > 640/2) {
    this._panel.transitionTo(640)
  } else {
    this._panel.transitionTo(0)
  }
}

<SlidingUpPanel
  ref={c => this._panel = c}
  draggableRange={{top: 640, bottom: 0}}
  onDragEnd={this._handleOnDragEnd}
/>

**Comment by huy-lv** [comment]
It's not work man, have you tried it before?
I tried it on iPad Air 2 and android: https://www.youtube.com/watch?v=WBK4i-YjUug

**Comment by octopitus** [comment]
Yes.

![mar-21-2018 16-33-31](https://user-images.githubusercontent.com/6346034/37702600-a562945e-2d25-11e8-90ee-08b0ec79c0c2.gif)

**Comment by octopitus** [comment]
Also remember to disable momentum by setting `allowMomentum={false}`

**Comment by huy-lv** [comment]
yeah, it's work, you forgot the most important thing :))

**Comment by ajoykarmakar459** [comment]
> ```js
> ref={c => this._panel = c}
>   draggableRange={{top: 640, bottom: 0}}
>   onDragEnd={this._handleOnDragEnd}
> />
> ```

This code isn't working anymore in the latest version of this library.

![Screenshot_1630134506](https://user-images.githubusercontent.com/23628008/131209828-3052a35d-525c-4d04-b8f2-d82a761a171f.png)
