### ISSUE TITLE
Start panel closed

### ISSUE THREAD

**Issue by msdevstep** [octopitus/rn-sliding-up-panel#41]
I can't figure out how to have the panel render closed on load. Is this supported?

**Comment by jwoertink** [comment]
This is what works for me

```javascript
<SlidingUpPanel visible={false}>

</SlidingUpPanel>
```

**Comment by octopitus** [comment]
Or you can even omit the `visible` property. Just:

```jsx
<SlidingUpPanel>

</SlidingUpPanel>
```

**Comment by msdevstep** [comment]
This does not work. It just makes the entire panel disappear.

**Comment by msdevstep** [comment]
I figured it out. This line in the 'render()' method is preventing the initial rendering.

 render() {
    if (!this.props.visible1) {
      return null
    }
   ...
}
