### ISSUE TITLE
Forcing backdrop over react navigation

### ISSUE THREAD

**Issue by jwoertink** [octopitus/rn-sliding-up-panel#42]
When I set `showBackdrop` to true, the backdrop doesn't extend up over the navigation when using [react-navigation](https://github.com/react-navigation/react-navigation). My guess is because the header is rendered at a higher level than the rest of the screen. 

<img width="408" alt="screen shot 2018-03-23 at 1 59 44 pm" src="https://user-images.githubusercontent.com/2391/37853121-792df7c4-2ea2-11e8-8dd1-e500ef0f7c19.png">

Is there a way around this? I'd like the backdrop to extend all the way like this.
<img width="411" alt="screen shot 2018-03-23 at 2 11 54 pm" src="https://user-images.githubusercontent.com/2391/37853502-36e81ece-2ea4-11e8-8cb6-29151dbafe20.png">

**Comment by octopitus** [comment]
A workaround solution, for now, is moving the panel to bottommost of components hierarchy, bellow the root navigator. Example: 

```jsx
// Navigator.js
import React from "react";
import { View, Text } from "react-native";
import { StackNavigator } from "react-navigation";

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Home'
  }

  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

export default StackNavigator({
  Home: { screen: HomeScreen }
});
```

```jsx
// App.js
import React from "react";
import { AppRegistry, View, Button, Text, TouchableOpacity } from "react-native";

import SlidingUpPanel from "rn-sliding-up-panel";

import Navigator from "./Navigator";

const styles = {
  container: {
    flex: 1
  },
  panel: {
    flex: 1,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center"
  }
};

class App extends React.Component {
  static router = Navigator.router;

  render() {
    return (
      <View style={styles.container}>
        <Navigator />
        <SlidingUpPanel visible>
          <View style={styles.panel}>
            <Text>Here is the content inside panel</Text>
          </View>
        </SlidingUpPanel>
      </View>
    );
  }
}

AppRegistry.registerComponent('App', () => App);
```

Let me know if it works for you.

**Comment by jwoertink** [comment]
Hmm... That might be ok; however, a little weird. So in my case, I have 2 different sliding panels that show up on the same page. They both go on the settings page
<img width="789" alt="screen shot 2018-03-24 at 5 03 20 pm" src="https://user-images.githubusercontent.com/2391/37870230-50325dae-2f85-11e8-8434-01ef6b2096d7.png">

I'm using some state on the settings page for opening and closing these panels. I'm not sure how that would work out if the panels are defined at the root. Maybe there's  away to bubble up from the settings page to the root or something? I'll mess around with it and see what I can come up with. Thanks for the suggestion!

**Comment by octopitus** [comment]
Use can use either redux/mobx (or any state management) or React's context. The new API of React's context is pretty slick.

**Comment by jwoertink** [comment]
cool. I'm gonna see if that new context is available in native now. If not, I'll try out redux. I've had a few others suggest that as well, so it sounds like that's the way to go. Thanks!
