### ISSUE TITLE
Panel Header be the Drag Handle

### ISSUE THREAD

**Issue by msdevstep** [octopitus/rn-sliding-up-panel#43]
I want to have just the panel header (peek) be the only part of the panel that allows the user to slide the panel with. So the content portion of the panel would not move the panel when the user drags on it. This will allow the content portion to contain scroll lists without moving the panel.

Does this make sense? Thank you for any assistance.

This package is really great by the way, I almost have it behaving exactly as it should, just have this one last request.

**Comment by octopitus** [comment]
Thanks @msdevstep. Will consider this.

**Comment by msdevstep** [comment]
Do you know any way I could make it only slide if the user tapped in the peek area, with the current implementation?

**Comment by octopitus** [comment]
Hey @msdevstep, with 1.2.0 you may pass function as children and attach drag handler to any view you want.
