### ISSUE TITLE
Enable ScrollView inside panel?

### ISSUE THREAD

**Issue by erichall** [octopitus/rn-sliding-up-panel#47]
Trying to enable a ScrollView inside the sliding panel but can't get the PaneHandlers to disable dragging again after you reached the end...
```
constructor(props) {
        super(props);
        this.state = {
            drag: false,
        };
        this._panResponder = PanResponder.create({
            onMoveShouldSetPanResponder: (e, gestureState) => {
                this.setState({ drag: true });
                return true;
            },
            onPanResponderRelease: (e, gestureState) => this.setState({drag: false}),
            onPanResponderTerminate: (e, gestureState) => this.setState({drag: false}),
        });
    }
```
and inside the component i'm just setting the panHandlers to the scrollView
```
<SlidingUpPanel
    showBackdrop={false}
    ref={c => this._panel = c}
    height={300}
    allowDragging={this.state.drag}
    draggableRange={{top: height, bottom: height - 180}} 
    visible={true}>
        <View style={styles.container}>
            <ScrollView   {...this._panResponder.panHandlers}>
            ....
            </ScrollView>
</SlidingUpPanel>
```

So it works fine the first time you enter the View and scroll up and down but Release and Terminate responder isn't kicking in when you start scrolling again.

**Comment by msdevstep** [comment]
Hey I just fixed this problem in my own app. Add the PanResponder to the outer view as well and any inner views that might be inside your scroll view. They seem to be stealing capture.

**Comment by msdevstep** [comment]
I was also seeing an issue where the sliding panel would snap closed when I updated the allowDragging prop. I have had to bring this component into my own project rather than using the package. I did this because there were some minor things that weren't working right. I will try to put together a pull request to fix these.

**Comment by erichall** [comment]
Hmm, to add the PanResponder to every view seems like a messy solution and not really sustainable in the long run. 

My end goal is to have the ScrollView to be able to scroll down when the sliding panel is all the way at the top of the main view, i.e the phone window height. And to drag the sliding panel down again should only happen when the scroll view is scrolled all the way to the top. 

That might have been a bad explanation but I would love some help with it :)

**Comment by octopitus** [comment]
@erichall That's nearly impossible since the ScrollView can bounce when it reaches top/bottom. Not to mention with FlatList/SectionList you may have pull to refresh or trigger load more data when it reaches the end of the list.

The simplest solution I can think about right now is passing the drag handlers to children and lets children decide which part of the the panel will handle dragging. Ex:

```jsx
const Content = ({dragHandlers}) => (
  <View style={styles.panelContainer}>
    <View {...dragHandlers} style={styles.panelHeader} />
    <ScrollView>
       // ...
    </ScrollView> 
  </View>
)

<SlidingUpPanel visible>
  {(dragHandlers) => <Content dragHandlers={dragHandlers}>}
</SlidingUpPanel>
```

**Comment by octopitus** [comment]
@erichall @msdevstep Just figured out a solution for this. Manually set `allowDragging` to false when users tap on ScrollView area and switch back to false when they release their finger. Example:

```jsx
<SlidingUpPanel allowDragging={this.state.allowDragging}>
    <ScrollView
      onTouchStart={() => this.setState({allowDragging: false})}
      onTouchEnd={() => this.setState({allowDragging: true})}
      onTouchCancel={() => this.setState({allowDragging: true})}>
      // ...
</SlidingUpPanel>
