### ISSUE TITLE
Start initially collapsed panel?

### ISSUE THREAD

**Issue by outaTiME** [octopitus/rn-sliding-up-panel#48]
Hi guys, any way to start the panel initially collapsed? or the only way is using transitionTo when componentDidMount?

Is a must to have feature (IMHO), thanks !!!

**Comment by outaTiME** [comment]
Here is a small example of what I'm looking for (but without initial render gap):

https://snack.expo.io/B120zQ-oM

**Comment by octopitus** [comment]
Hi @outaTiME, this feature will have in next version. Please have a look into this PR #46. Almost done. I still need some times to verify it works correctly.

**Comment by RohanChawla01** [comment]
@outaTiME is the collapsed panel feature done?

**Comment by barnir** [comment]
@outaTiME tried your solution and it works.. but i see the panel when entering my component and then iot collapses, any tip here?

**Comment by octopitus** [comment]
Seems like `visible` props is not necessary? I'm open for discussion.

**Comment by barnir** [comment]
I Did some attempts with visible prop.. but it ended up being on pulled up state when set to true... also did attempts to change drag range on component did mount.. and it messes with pull up.. so for what i did is change the duration of transitionTo to 0.. but it is still visible.. will give some attempts tomorrow

**Comment by thierryfornetti** [comment]
I've solved by changing the `top` value of `draggableRange`
```
constructor( props ) {
        super(props);

        this.state = {
            slidableMaxHeight: 120,
        };
}

componentDidMount() {
        this.setState({ slidableMaxHeight: height - StatusBar.currentHeight });
}

render() {
        return (
            <View >
                ...
                <SlidingUpPanel
                    visible
                    draggableRange={{
                        top: this.state.slidableMaxHeight,
                        bottom: 120,
                    }}
                    showBackdrop={false}
                    onDrag={this.onSlidingPanelDrag}
                    >
                    <View style={{flex: 1}}>
                         ...
                    </View>
                </SlidingUpPanel>
            </View>
        );
}
```

**Comment by Bobobrien92** [comment]
I was able to get it working how I wanted by editing the SlidingPanel.js constructor code

this._animatedValueY = this.state.visible ? -top : -bottom
==>
 this._animatedValueY = this.state.visible ? this.props.startCollapsed ? -bottom : -top : -bottom

**Comment by octopitus** [comment]
Thanks @Bobobrien92. Much appreciated if you can send a PR.

**Comment by Bobobrien92** [comment]
https://github.com/octopitus/rn-sliding-up-panel/pull/51

**Comment by octopitus** [comment]
As v1.2.1 you can use `startCollapsed` prop to show the panel at bottom (within draggable range).

**Comment by zenVentzi** [comment]
v. 2.3.3 `startCollapsed` prop is not available. Or at least that's what typescript is telling me.

I'm not sure I am at the correct issue, but what I am trying to achieve is something like the image below. I want The user to be able to catch that and drag up until the screen is on.
![image](https://user-images.githubusercontent.com/11378653/66633167-e1995680-ec12-11e9-835e-db12ccb1b1ac.png)

**Comment by octopitus** [comment]
@zenVentzi 
```js
const animatedValue = new Animated.Value(startingPoint);
<SlidingUpPanel
  animatedvalue={animatedValue}
  // other props
/>
```

Keep in mind that you should not put `animatedValue` in render function if you don't want to ruin the performance of your app.
