### ISSUE TITLE
delete topbar height 

### ISSUE THREAD

**Issue by cinder92** [octopitus/rn-sliding-up-panel#5]
Hello, this issue can be fixed, deleting the `statusBarHeight`, you have a Math calc, that remove `statusBarHeight` from `windowHeight` and its causing this issue

![captura de pantalla 2017-05-24 a la s 01 30 38](https://cloud.githubusercontent.com/assets/4725556/26389654/a171d50a-4020-11e7-9735-a24ce75acfad.png)

May be, you need to let the user set the height of panel

**Comment by octopitus** [comment]
If the `StatusBar` is translucent or hidden, you need change the height of panel by using the `draggableRange` props. Like this:

```jsx
const {height} = Dimensions.get('window')

<SlidingUpPanel draggableRange={{top: height, bottom: 0}}>
// Your stuff
</SlidingUpPanel>
```

**Comment by octopitus** [comment]
Nice screenshot by the way.

**Comment by cinder92** [comment]
@octopitus ok then! thank you very much 👍

**Comment by cinder92** [comment]
mmm @octopitus still not working :(

**Comment by octopitus** [comment]
Hm, let me look at it when have time. I'm busy right now.

**Comment by octopitus** [comment]
@cinder92 Hi, please upgrade component to version `1.1.3`. It fixes your issue. Now you can just:
```js
const {height} = Dimensions.get('window')

<SlidingUpPanel draggableRange={{top: height, bottom: 0}}>
// Your stuff
</SlidingUpPanel>
```
