### ISSUE TITLE
put scrollview in panel

### ISSUE THREAD

**Issue by xsailor511** [octopitus/rn-sliding-up-panel#52]
put a scrollview in SlidingUpPanel may lead to gesture problem,how to solve this problem?
I need to put a FlatList in SlidingUpPanel!

**Comment by Bobobrien92** [comment]
Check the past issues for how to handle scrollviews.  I had the same problem and found a working solution already in the project issues

**Comment by octopitus** [comment]
[ScrollView insides panel](https://github.com/octopitus/rn-sliding-up-panel/blob/master/demo/ScrollViewInsidePanel.js)
