### ISSUE TITLE
Keyboard overlapping the fields

### ISSUE THREAD

**Issue by renanboni** [octopitus/rn-sliding-up-panel#53]
Hello everyone, today I was implementing this SlidingUp Panel and everything seems to look pretty cool, but there's a little problem, when I touch a Input Text which is inside the panel, the keyboard overlaps the Input instead to push the layout above. Anyone faced this problem?

** I already tried to use KeyboardAvoidingView but no success.

Thank you.

**Comment by octopitus** [comment]
Close as it's fixed in v2.
