### ISSUE TITLE
Minimum Height

### ISSUE THREAD

**Issue by AustinErck** [octopitus/rn-sliding-up-panel#55]
A change where we will always have a small amount of the slider showing would be nice. If there was a way to animate between this collapsed view and the fully expanded view that would be cool too. Similar to how the Spotify or Apple Music music player works.

**Comment by Bobobrien92** [comment]
You have to set the appropriate bottom limit of the draggable range and ensure the component has the visible prop enabled.

            draggableRange={{
              top: height -145,
              bottom: panelHeight
            }}

**Comment by octopitus** [comment]
Thanks @Bobobrien92. That's correct.
