### ISSUE TITLE
not working on android with mapview

### ISSUE THREAD

**Issue by Danelund** [octopitus/rn-sliding-up-panel#56]
Working fine on iOS, but not showing up on Android.

Package.json:
```
"dependencies": {
    "axios": "^0.18.0",
    "dezalgo": "^1.0.3",
    "expo": "^27.0.1",
    "firebase": "^4.12.1",
    "geolib": "^2.0.24",
    "lodash": "^4.17.5",
    "native-base": "^2.3.10",
    "npm": "^4.6.1",
    "qs": "^6.5.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
    "react-native-LoopAnimation": "^0.1.0",
    "react-native-animatable": "^1.3.0",
    "react-native-background-fetch": "^2.4.2",
    "react-native-background-geolocation": "^2.12.0-beta.4",
    "react-native-fcm": "^15.0.2",
    "react-native-image-progress": "^1.1.0",
    "react-native-page-control": "^1.1.1",
    "react-navigation": "^2.0.1",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-persist": "^5.7.2",
    "redux-thunk": "^2.2.0",
    "rn-sliding-up-panel": "^1.2.0"
```

The content is fired, and If showBackdrop is true, entire screen will me blacked out, once visible = true, but panel itself does not appear.

`<View style={{flex: 1}}>
            <MapView style={{flex: 1}} 
            onRegionChangeComplete={this.onRegionChangeComplete} 
            showsUserLocation={true}
            userLocationAnnotationTitle=""
            loadingEnabled={true}
            onPress={this._onMapPress}
            cacheEnabled={Platform.OS === 'android' ? true : false}>
            </MapView>
            <SlidingUpPanel visible={this.state.visible} allowDragging={false}
            draggableRange={{ top: sliderTop, bottom:0 }}
            showBackdrop={false}
            onRequestClose={() => this.setState({visible: false})}>
            <View style={{flex:1, backgroundColor: 'white'}}></View>
            </SlidingUpPanel>
            </View>`

**Comment by hanishcodebrew** [comment]
I am facing the same issue as mentioned by @Danelund

**Comment by octopitus** [comment]
@hanishcodebrew can you please create another issue? Follow the issue template and provide more details. I'm gonna close this.

**Comment by SethArchambault** [comment]
This sounds like what I'm encountering as well - though it doesn't happen all the time, just occasionally when tapping a text area.
