### ISSUE TITLE
Sliding up Panel with Keyboard

### ISSUE THREAD

**Issue by EkamKalsi** [octopitus/rn-sliding-up-panel#6]
Hey, so I am using the Bottom up slider as shown in the demo file. In my case the bottom up slider has two textboxes inside it, and I am doing my development for Android OS. Whenever, I press the textbox on the panel, it never goes up. I have made appropriate changes to my AndroidManifest.xml. Also, I have tried enclosing the sliding panel with a KeyboardAvodingView, however, it doesnt seem to be working.

![pagewhichrendersslider](https://user-images.githubusercontent.com/7677086/27044402-79ed7ae8-4f6b-11e7-8e80-0ad18a002c90.PNG)
![slider](https://user-images.githubusercontent.com/7677086/27044401-79ed0c8e-4f6b-11e7-9004-1d4d6da7b85f.PNG)
![slider_styles](https://user-images.githubusercontent.com/7677086/27044403-79effa0c-4f6b-11e7-9af4-57acf8f81047.PNG)

**Comment by octopitus** [comment]
Thanks for reporting the issue @EkamKalsi . I will look into it.

**Comment by octopitus** [comment]
Hi @EkamKalsi, to show the panel when tap on input, you should do something like:
```js
<TextInput onFocus={() => this.setState({visible: true}) />
```
And the panel should be:
```
<SlidingUpPanel visible={this.state.visible} />
```
