### ISSUE TITLE
Adding an Animation to the Header while dragging the Panel Up and Down

### ISSUE THREAD

**Issue by ameenmattar** [octopitus/rn-sliding-up-panel#61]
Is there any way to add an animation for the header 'Bottom Sheet' while dragging the panel up to let the header disappear , and when dragging the panel down to see again the Header 'Bottom Sheet'
@octopitus 

**Thank you in advance**

**Comment by octopitus** [comment]
Refer to the BottomSheet demonstration [here](https://github.com/octopitus/rn-sliding-up-panel/blob/master/demo/BottomSheet.js)
