### ISSUE TITLE
set backdrop opacity

### ISSUE THREAD

**Issue by jiradeto** [octopitus/rn-sliding-up-panel#62]
I am trying to implement sliding-up panel at the bottom of the screen and I found out that the backdrop opacity is darken. 

My screenshort heres.

<img width="316" alt="screen shot 2561-06-27 at 12 11 21" src="https://user-images.githubusercontent.com/16756648/41954047-49bd7ddc-7a03-11e8-92e8-44db3b735022.png">

**I would like to know is there any option to set opacity (or disable backdrop opacity).**
This is my expectation.

<img width="318" alt="screen shot 2561-06-27 at 12 11 29" src="https://user-images.githubusercontent.com/16756648/41954083-946d55be-7a03-11e8-96d8-d46994a529a0.png">

thank you in advance.

**Comment by octopitus** [comment]
You can remove backdrop completely with `showBackdrop={false}`.

**Comment by jiradeto** [comment]
thank you very much 😀😀😀😀
