### ISSUE TITLE
Unable to control screen outside panel.

### ISSUE THREAD

**Issue by Kosiarznerek** [octopitus/rn-sliding-up-panel#63]
Hello,
Actually, it's not an issue, but I don't know where "suggestions" should be posted. Let's assume that currently, our slide up panel takes 50% of the screen (bottom part). Above it, the user is able to see the application content but is not able to control it. What is more, there is no property which will allow us as developers to disable such a feature. BTW great project.

**Comment by deden** [comment]
In my case this related to `showBackdrop`. Somehow the backdrop still being rendered though the position below the `draggableRange`.

**Comment by epurban** [comment]
Hi, were you able to fix this issue?

**Comment by ponjoru** [comment]
@epurban set property showBackdrop to 'false'. That worked for me

**Comment by markmssd** [comment]
In my case I wanted `showBackdrop` to be `true`. When initialized to true, I had this problem, so I'm initializing it to `false` in the state, then in the `onDragStart={() => this.setState({ showBackdrop: true )}` instead. Pretty hacky, but does the job.

**Comment by octopitus** [comment]
Close as it fixed in v2.
