### ISSUE TITLE
toValue not working

### ISSUE THREAD

**Issue by shaikhaffan** [octopitus/rn-sliding-up-panel#64]
hey i have a state : transiction:{
        toValue : 100,
        duration :2000,        
      }

passing in transitionTo property of SlidingUpPanel, but not working

**Comment by shaikhaffan** [comment]
I am passing my object like that see in the example 

<SlidingUpPanel     
                      visible={this.state.checkoutPanel}
                      showBackdrop={false}
                      transitionTo={
                        this.state.transitionTo
                      }
                    >
                    <Checkoutslide   />
                    </SlidingUpPanel>

**Comment by octopitus** [comment]
`transitionTo` is a method. You must use the ref of the component.

```js
<SlidingUpPanel ref={c => this._panel = c}>
{ //... }
</SlidingUpPanel>

// And later on 
// this._panel.transitionTo(...)
```
