### ISSUE TITLE
SlidingUpPanel.render()

### ISSUE THREAD

**Issue by kwkeat** [octopitus/rn-sliding-up-panel#65]
SlidingUpPanel.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

Using the example provided I am getting this error.
```
render() {
    return (
      <View style={styles.container}>
        <Button title="Show panel" onPress={() => this.setState({ visible: true })} />
        <SlidingUpPanel
          visible={this.state.visible}
          onRequestClose={() => this.setState({ visible: false })}
        >
          <View style={styles.container}>
            <Text>Here is the content inside panel</Text>
            <Button title="Hide" onPress={() => this.setState({ visible: false })} />
          </View>
        </SlidingUpPanel>
      </View>
    );
  }
```

**Comment by ignivaravinderrikhi** [comment]
+1

**Comment by kwkeat** [comment]
@octopitus any info on this?

**Comment by balamcan** [comment]
i ve got modify the source code of the library, maybe the versions we are using are old (reactjs and react native) for this package is coded, i fixed change the code in the render return method:

actually
```
render() {
    if (!this.state.visible) {
      return null
    }

    return [this._renderBackdrop(), this._renderContent()]
  }
```

modified
  ```
render() {
    if (!this.state.visible) {
      return null
    } else

      return <Animated.View>{this._renderBackdrop()}{this._renderContent()}</Animated.View>
  }
```

need specific in the docs for what versions package code are supporting in this library, i hope they will make a supporting patch or make a update of the documentation

Regards!

**Comment by octopitus** [comment]
Thanks @balamcan. Returning an array of elements in render() is supported in React 16.x. You may be using version an older version. Consider upgrading.

Lets me update the doc.
