### ISSUE TITLE
Keyboard overlapping fields and unable to use KeyboardAvoidingView.

### ISSUE THREAD

**Issue by nitish1099** [octopitus/rn-sliding-up-panel#67]
how do I manage to push fields up with the keyboard?

**Comment by nasungtae** [comment]
<KeyboardAvoidingView style={styles.bottomView}
                        keyboardVerticalOffset={Platform.OS == 'ios'? 100 : 110 } 
                        behavior="padding" enabled>
                // .. contents
              </KeyboardAvoidingView>

**Comment by nasungtae** [comment]
<KeyboardAvoidingView style={styles.bottomView}
                        keyboardVerticalOffset={Platform.OS == 'ios'? 100 : 110 } 
                        behavior="padding" enabled>
             

              </KeyboardAvoidingView>
