### ISSUE TITLE
Touchables on panel not very responsive

### ISSUE THREAD

**Issue by dylanrhodius** [octopitus/rn-sliding-up-panel#71]
I have a touchable on the panel which is supposed to trigger a function when pressed.

Many times when pressing this touchable, my android phone thinks Im trying to slide the panel instead and so the sliding gets activated.

Any thoughts, tips?

**Comment by stefanuswendy** [comment]
i got the same issue, still cant find how to solve this.
need some help here

**Comment by dylanrhodius** [comment]
@stefanuswendy 
I ended up setting the SlidingUpPanel `allowDragging` prop to `false` when holding/pressing the touchables by doing this below. Let me know if that works/doesn't for you.

// Initiate panel allowing it to be draggable
`
  constructor(props) {
    super(props);
    this.state = {
      allowDragging: true,
    };
  }
`

// Function to enable/disable panel dragging
`
  handlePanelDragging = () => {
    this.setState({allowDragging: !this.state.allowDragging })
  }
`

`
<SlidingUpPanel
    allowDragging={this.state.allowDragging}>                 //Dragging depends on state
    YOUR OTHER CONTENT IN HERE
      <TouchableOpacity
         onPressIn={() => {this.handlePanelDragging()}}     //Call function to disable dragging
         onPressOut={() => {this.handlePanelDragging()}}  //Call function to enable dragging
      </TouchableOpacity>
</SlidingUpPanel>`

**Comment by stefanuswendy** [comment]
@dylanrhodius Workaround WORKED ! thanks alot

**Comment by kruulik** [comment]
This works for me most of the time, except when swiping down fast on the inner list.

**Comment by ameenmattar** [comment]
@dylanrhodius how can do this if i have a textInput in it and not a touchableOpacity.

my problem is that i can not select a text input and start writing because the panel is so sensitive on drag.

**Comment by dylanrhodius** [comment]
@ameenmattar is this still a problem?
Do you think maybe firing the handlePanelDragging function upon the `focus/blur` of your `textInput` would work?

**Comment by octopitus** [comment]
Sorry totally forgot this. Now with v2 you can increase the minimum distance & velocity threshold. Some devices seems sensitive with gesture.

**Comment by octopitus** [comment]
I will close this issue. If you still have the problem, feel free to open another one.

**Comment by sinodko** [comment]
@octopitus could you tell me more about solution of this one in v2?
