### ISSUE TITLE
How to use transitionTo method.

### ISSUE THREAD

**Issue by KumarAbhirup** [octopitus/rn-sliding-up-panel#72]
Please there let be an example about that. I'm desperately waiting to use it but can't find its how to. Please help.

**Comment by minhtamwebmaster** [comment]
<SlidingUpPanel
                    //height={20}
                    ref={"abc"}
                    visible={this.state.visible}
                    draggableRange={{top: 500, bottom: 70}}
                    startCollapsed={true}
                    onRequestClose={() => this.setState({visible: false})}>
                    <View style={{ flex: 1, backgroundColor: '#FFF', borderTopLeftRadius: 8, borderTopRightRadius: 8 }}>
                        <View
                            style={{ height: 50, backgroundColor: '#00ad4e', borderTopLeftRadius: 8, borderTopRightRadius: 8, justifyContent: 'center', alignItems: 'center' }}
                        >
                            <Text style={{ color: '#FFF', fontWeight: 'bold' }}>DANH SÁCH XẢ HÀNG</Text>
                        </View>
                    </View>
                </SlidingUpPanel>

AND USE

this.refs.abc.transitionTo(700, 100);

**Comment by TheWeeezel** [comment]
this can not be considered fixed it does not work when i use it. 

it gives me an error a stateless component can not have refs.

**Comment by octopitus** [comment]
@TheWeeezel Can you show me the code describe how you get the ref?
