### ISSUE TITLE
whole component itself is not working

### ISSUE THREAD

**Issue by GaneshSaiKumar** [octopitus/rn-sliding-up-panel#81]
I have tried using it, but it's not popping any modal or slider kind of things up on clicking the button.

**Comment by SaravanakumarSubramanian** [comment]
change the property visible to true

render() {
    return (
      <View style={styles.container}>
        <Button title='Show panel' onPress={() => this.setState({visible: true})} />
        <SlidingUpPanel
          `visible={true}  <===Change this property`
          onRequestClose={() => this.setState({visible: false})}>
          <View style={styles.container}>
            <Text>Here is the content inside panel</Text>
            <Button title='Hide' onPress={() => this.setState({visible: false})} />
          </View>
        </SlidingUpPanel>
      </View>
    )
  }
