### ISSUE TITLE
Limit first animation to the middle of the screen & still be draggable all the way to the top

### ISSUE THREAD

**Issue by 4rtikk** [octopitus/rn-sliding-up-panel#84]
This is not acctually a issue, but i'm unsuccessfully trying to find a way to limit the first animation to the middle of the screen but still be draggable all the way to the top if the user chooses to, anyone can give a little help on how to do this ?

**Comment by octopitus** [comment]
With v2 you can:

```js

 _moveToMiddle = () => {
    const animation = Animated.timing(this._animatedValue, {
      toValue: MIDDLE_OF_SCREEN,
    })

    animation.start()
  }

```
