### ISSUE TITLE
Gesture state on drag start/end

### ISSUE THREAD

**Issue by husnaingoldev** [octopitus/rn-sliding-up-panel#92]
### Gesture state when drag starts and end

Tried a pull request but permission denied

if possible please replace following line of code in SlidingUpPanel.js
```this.props.onDragStart(-this._animatedValueY)```       
with
```this.props.onDragStart(-this._animatedValueY, gestureState)```     

and this line 
```const cancelFlick = this.props.onDragEnd(-this._animatedValueY)``` 
with
```const cancelFlick = this.props.onDragEnd(-this._animatedValueY, gestureState)```   
 
Thanks.

**Comment by octopitus** [comment]
Thanks @husnaingoldev. Can you try this on version 2? (npm install rn-sliding-up-panel@next) On version 2, `onDragStart` and `onDragEnd` are called with gesture state as 2nd param just like how you described here.

**Comment by husnaingoldev** [comment]
@octopitus Thanks man 👍
