### ISSUE TITLE
backdrop touch events

### ISSUE THREAD

**Issue by mojtaba-hajishah** [octopitus/rn-sliding-up-panel#93]
### Issue Description

Hi, Thanks for this great lib.
Is there a way to completely disable touch events on content behind the panel when the panel is open?
my panel is 50% of device height. the issue is that the content behind backdrop are touchable.
I want to disable touch events on the content behind the backdrop when the panel is open and just close the panel on any backdrop touches.

ps: At first, I installed version 1, and did what you mentioned in [this issue](https://github.com/octopitus/rn-sliding-up-panel/issues/15), but it did not work for me.
Then I installed version 2, and in this version you have removed function onRequestClose().
so I could not achieve this in neither of versions.

---
### Environment
* Version: 2
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by octopitus** [comment]
This is actually an issue that pointer event is not updated correctly. A fix has been released. Checkout the latest version (`npm install rn-sliding-up-panel@latest`).

**Comment by helloeyesimple** [comment]
hi, I want to disable backdrop touch too. I don't think latest version can achieve that. Please advise
